SPEED:
  Enable: false
  List:
    - Kolbi
    - SPEED
SLOW:
  Enable: false
  List:
    - Kolbi
    - SLOW
FAST_DIGGING:
  Enable: false
  List:
    - Kolbi
    - FAST_DIGGING
SLOW_DIGGING:
  Enable: false
  List:
    - Kolbi
    - SLOW_DIGGING
INCREASE_DAMAGE:
  Enable: false
  List:
    - Kolbi
    - INCREASE_DAMAGE
HARM:
  Enable: false
  List:
    - Kolbi
    - HARM
HEAL:
  Enable: false
  List:
    - Kolbi
    - HEAL
JUMP:
  Enable: false
  List:
    - Kolbi
    - JUMP
CONFUSION:
  Enable: false
  List:
    - Kolbi
    - CONFUSION
REGENERATION:
  Enable: false
  List:
    - Kolbi
    - REGENERATION
DAMAGE_RESISTANCE:
  Enable: false
  List:
    - Kolbi
    - DAMAGE_RESISTANCE
FIRE_RESISTANCE:
  Enable: false
  List:
    - Kolbi
    - FIRE_RESISTANCE
WATER_BREATHING:
  Enable: false
  List:
    - Kolbi
    - WATER_BREATHING
INVISIBILITY:
  Enable: false
  List:
    - Kolbi
    - INVISIBILITY
BLINDNESS:
  Enable: false
  List:
    - Kolbi
    - BLINDNESS
NIGHT_VISION:
  Enable: false
  List:
    - Kolbi
    - NIGHT_VISION
HUNGER:
  Enable: false
  List:
    - Kolbi
    - HUNGER
WEAKNESS:
  Enable: false
  List:
    - Kolbi
    - WEAKNESS
POISON:
  Enable: false
  List:
    - Kolbi
    - POISON
WITHER:
  Enable: false
  List:
    - Kolbi
    - WITHER
HEALTH_BOOST:
  Enable: false
  List:
    - Kolbi
    - HEALTH_BOOST
ABSORPTION:
  Enable: false
  List:
    - Kolbi:
      -10
    - ABSORPTION
SATURATION:
  Enable: false
  List:
    - Kolbi
    - SATURATION
GLOWING:
  Enable: false
  List:
    - Kolbi
    - GLOWING
LEVITATION:
  Enable: false
  List:
    - Kolbi
    - LEVITATION
LUCK:
  Enable: false
  List:
    - Kolbi
    - LUCK
UNLUCK:
  Enable: false
  List:
    - Kolbi
    - UNLUCK