# PotionArmor Plugin Configuration
# ---
# Potion Effects
# should support all existing potion effects
# regenerating the default config will give you a list of options in the comments
# ---
# Disguise Effects:
# "entity:" is a string of parameters parsed as if passed to "/disguise <entity>"
# more info at https://www.spigotmc.org/wiki/lib-s-disguises-using-the-commands/
# or by using /disguisehelp <disguisetype>
#
# the "libsdisguises.seethrough" permission node is useful for staffers
# consider aliasing a command to toggle. will need to relog for the perm to take effect
# ---
# Trail Effects:
# see effects at https://github.com/Rosewood-Development/PlayerParticles/blob/master/src/main/java/dev/esophose/playerparticles/particles/ParticleEffect.java
# see styles at https://github.com/Rosewood-Development/PlayerParticles/blob/master/src/main/java/dev/esophose/playerparticles/styles/DefaultStyles.java
# ---

meta:
  language_loc: language.yml
  version: 1.0
  # async-multithreading options:
  async: true
  threads: 4
  maxThreads: 10
  capacity: 200 # thread queue job capacity, will reject new jobs after full
  timeout: 60 # how long to wait before killing idle threads
  unit: SECONDS # timeout time unit

SupportedEffects: ""

Defaults:
  disguise: cow

Effects:
  item1:
    loreline: "my awesome lore"
    slot: any
    effect1:
      enable: false
      type: trail
      effect: entity_effect
      style: overhead
      data:
        type: ordinary_color
        r: 0
        g: 100
        b: 100
        # must be 0-255
        # 999,999,999 is rainbow
        # 998,998,998 is random
    effect2:
      enable: false
      type: effect
      effect: minecraft:regeneration
      level: 1
    effect3:
      enable: false
      type: trail
      effect: dust_color_transition
      style: overhead
      data:
        type: color_transition
        r: 0
        g: 100
        b: 0
        r2: 0
        g2: 0
        b2: 100
        # must be 0-255
        # 999,999,999 is rainbow
        # 998,998,998 is random
    effect4:
      enable: false
      type: trail
      effect: note
      style: overhead
      data:
        type: note_color
        note: 5
        # must be 0 - 24
        # 99 is random
        # 98 is rainbow
    effect5:
      enable: false
      type: trail
      effect: vibration
      style: overhead
      data:
        type: vibration
        duration: 40
        # arrival time in ticks
    effect6:
      enable: false
      type: trail
      effect: block
      style: overhead
      data:
        type: material
        material: stone
  item2:
    loreline: "my second awesome lore"
    slot: hand
    effect1:
      enable: false
      type: effect
      effect: minecraft:regeneration
      level: 1
  item3:
    loreline: "my third awesome lore"
    slot: hand
    effect1:
      enable: false
      type: disguise
      entity: creeper setIgnited true
      # entity is a string of parameters parsed as if passed to "/disguise <entity>"
      # more info at https://www.spigotmc.org/wiki/lib-s-disguises-using-the-commands/
      # or by using /disguisehelp <disguisetype>
