name: ${project.artifactId}
author: tWizT3d_dreaMr
version: ${project.version}
main: me.tWizT3d_dreaMr.PotionArmour.main
commands:
   Pareset:
      description: Reset players effects.
      usage: pareset <player>
permissions:
  Potionarmor.pareset:
    default: op
    description: Allows the player to Pareset.
api-version: 1.18